sonar.projectKey=jooservices_flickr
sonar.projectName=flickr
sonar.organization=jooservices
sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=build/coverage/matrix/clover-Arch.xml,build/coverage/matrix/clover-Unit.xml,build/coverage/matrix/clover-Integration.xml
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.github/**,vendor/**,coverage/**,build/**
